import type { Metadata } from 'next';
import './globals.css';
import HeaderNav from '@/components/layout/HeaderNav';
import FooterNav from '@/components/layout/FooterNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderNav />
        {children}
        <FooterNav />
      </body>
    </html>
  );
}
